### ISSUE TITLE
ProductName: Unknown

### ISSUE THREAD

**Issue by shuk777** [google/go-sev-guest#84] opened 2023-09-20 07:14 UTC
Hi,there.

d.Product() returns product name `SevProduct_SEV_PRODUCT_UNKNOWN` while I'm using model Milan for sure. Do i need to run a command like `snphost import` to set CPU id value for my guests?

**Comment by deeglaze** [comment] 2023-09-27 02:58
The product name is specified by the AMD KDS specification https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/57230.pdf as derived directly from Cpuid_0000_0001_EAX as computed in abi/abi.go. What does /proc/cpuinfo tell you about the family and model numbers?

**Comment by shuk777** [comment] 2023-10-10 03:11
```
cpu family      : 25
model           : 1
model name      : AMD EPYC 7413 24-Core Processor
```

`dmesg | grep SEV` gives:

```
[    1.100229] SEV-SNP: RMP table physical address 0x0000000025e00000 - 0x00000000566fffff
[   17.326099] ccp 0000:27:00.1: SEV API:1.52 build:4
[   17.326109] ccp 0000:27:00.1: SEV-SNP API:1.52 build:4
[   17.388670] SEV supported: 410 ASIDs
[   17.388671] SEV-ES and SEV-SNP supported: 99 ASIDs
[ 1889.982867] SEV_GET_ID command is deprecated, use SEV_GET_ID2
```

**Comment by deeglaze** [comment] 2023-10-16 15:45
Is this dmesg from the guest or the host? It's up to the VMM (e.g., Qemu) to present the correct CPUID table entries for the AMD Milan-B1 machine.

**Comment by aep** [comment] 2023-12-06 09:10
the amd docs are pretty confusing. they say that for milan the ext family is supposed to be `0xA` which would be Opteron Era. Milan is `0x19` and of course that what we observe on the guest

```
CPU Info for type #0:
------------------
  arch       : x86
  purpose    : general
  vendor_str : `AuthenticAMD'
  vendor id  : 1
  brand_str  : `AMD EPYC-Milan-v2 Processor'
  family     : 15 (0Fh)
  model      : 1 (01h)
  stepping   : 1 (01h)
  ext_family : 25 (19h)
  ext_model  : 1 (01h)
  num_cores  : 1
  num_logical: 1
  tot_logical: 1
  affi_mask  : 0x00000001
  L1 D cache : 32 KB
  L1 I cache : 32 KB
  L2 cache   : 512 KB
  L3 cache   : 32768 KB
  L4 cache   : -1 KB
  L1D assoc. : 8-way
  L1I assoc. : 8-way
  L2 assoc.  : 8-way
  L3 assoc.  : 16-way
  L4 assoc.  : -1-way
  L1D line sz: 64 bytes
  L1I line sz: 64 bytes
  L2 line sz : 64 bytes
  L3 line sz : 64 bytes
  L4 line sz : -1 bytes
  L1D inst.  : -1
  L1I inst.  : -1
  L2 inst.   : -1
  L3 inst.   : -1
  L4 inst.   : -1
  SSE units  : 64 bits (authoritative)
  code name  : `EPYC (Milan)'
  features   : fpu vme de pse tsc msr pae mce cx8 apic mtrr sep pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht pni pclmul ssse3 cx16 sse4_1 sse4_2 syscall movbe popcnt aes xsave osxsave avx mmxext nx fxsr_opt rdtscp lm lahf_lm cmp_legacy abm misalignsse sse4a 3dnowprefetch osvw fma3 f16c rdrand avx2 bmi1 bmi2 sha_ni rdseed adx hypervisor
```

**Comment by deeglaze** [comment] 2024-04-02 19:50
I'm going to close this as a duplicate of [Issue#115](https://github.com/google/go-sev-guest/issues/115). The product name handling should become much simpler when the planned AMD SEV-SNP firmware update adds family/model/stepping values directly to the attestation report.

**Closed by deeglaze** 2024-04-02 19:50 UTC
