### ISSUE TITLE
Issue when running attestation on Genoa CPU

### ISSUE THREAD

**Issue by daniel-weisse** [google/go-sev-guest#103] opened 2024-01-23 11:27 UTC
I'm currently trying out SEV-SNP attestation on a Genoa CPU, AMD EPYC 9124 16-Core to be precise.
I'm running into issues when verifying the attestation.

Using the following sample code, calling `verify.RawSnpReport` throws the error `could not recreate attestation from report: unknown product name (new stepping published?): "Genoa"`

```Go
package main

import (
	_ "embed"
	"fmt"

	"github.com/google/go-sev-guest/client"
	"github.com/google/go-sev-guest/proto/sevsnp"
	"github.com/google/go-sev-guest/verify"
	"github.com/google/go-sev-guest/verify/trust"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	// ask_ark_genoa.cert from https://download.amd.com/developer/eula/sev/ask_ark_genoa.cert
	//go:embed ask_ark_genoa.cert
	askArkGenoaVcekBytes []byte
	// ask and ark pem certificates from https://kdsintf.amd.com/vcek/v1/Genoa/cert_chain
	//go:embed ask_genoa.pem
	askGenoaPEM []byte
	//go:embed ark_genoa.pem
	arkGenoaPEM []byte
)

func main() {
	// Get report
	reportData := [64]byte{}
	quoteProvider, err := client.GetQuoteProvider()
	if err != nil {
		panic(err)
	}
	reportRaw, err := quoteProvider.GetRawQuote(reportData)
	if err != nil {
		panic(err)
	}

	// Set up verification
	genoaRootCert := new(trust.AMDRootCerts)
	genoaRootCert.Product = "Genoa"
	if err := genoaRootCert.Unmarshal(askArkGenoaVcekBytes); err != nil {
		panic(err)
	}
	if err := genoaRootCert.Decode(askGenoaPEM, arkGenoaPEM); err != nil {
		panic(err)
	}
	verifyOpts := &verify.Options{
		Product: &sevsnp.SevProduct{
			Name:            sevsnp.SevProduct_SEV_PRODUCT_GENOA,
			MachineStepping: &wrapperspb.UInt32Value{Value: 2},
		},
		CheckRevocations: true,
		Getter:           trust.DefaultHTTPSGetter(),

		TrustedRoots: map[string][]*trust.AMDRootCerts{
			"Genoa": {genoaRootCert},
		},
	}

	// Verify report
	err = verify.RawSnpReport(reportRaw, verifyOpts)
	fmt.Println(err)
}
```

Looking at the code, a map is used to determine the stepping of the CPU for which the VCEK was issued: https://github.com/google/go-sev-guest/blob/f912a0a5e11e9aeb1ab8a3ceb617d8a135901a8b/kds/kds.go#L96-L102

The VCEK I'm receiving from the AMD API simply contains `Genoa` for its `productName` certificate extension, so it never matches any of the values in this map.

**Comment by deeglaze** [comment] 2024-01-24 17:26
You can confirm the SIGNING_KEY field of your report is 0 for VCEK? If so, this is a problem AMD should address, since the TCB_VERSION is really supposed to be interpreted according to the stepping value.

**Comment by deeglaze** [comment] 2024-02-03 05:48
No word yet. I'll send a ping on Monday, but I should see them in person on Wednesday if they don't see the email.

**Comment by deeglaze** [comment] 2024-02-08 16:33
I got word back, and they want the exact HTTP GET request used, so @daniel-weisse do you have the TCB_VERSION and CHIP_ID that I could forward to AMD? Feel free to email me dionnaglaze@google.com to not make that information public.

**Comment by deeglaze** [comment] 2024-02-08 16:39
Also also, did your call to RawSnpReport specify the product in the Options argument? The default product used when it's not available in the Attestation message (which isn't in RawSnpReport) or the Options argument is to use Milan-B1. Perhaps I should add a warning or simply error when RawSnpReport is used without a specified product.

**Comment by daniel-weisse** [comment] 2024-02-09 08:26
> Feel free to email me [dionnaglaze@google.com](mailto:dionnaglaze@google.com) to not make that information public.

Thank, sent the email

> did your call to RawSnpReport specify the product in the Options argument?

Yes, as shown in my sample code, `verify.Options.Product.Name` it is set to `sevsnp.SevProduct_SEV_PRODUCT_GENOA`, and `verify.Options.Product.MachineStepping` is set to `2` (though any value here produced the same error irrc).

> AMD has acknowledged that this is a bug and they are working to fix KDS.

Good to hear, thank you for your help with this

**Comment by deeglaze** [comment] 2024-04-02 19:46
I'm going to close this as a duplicate of [Issue#115](https://github.com/google/go-sev-guest/issues/115)

**Closed by deeglaze** 2024-04-02 19:46 UTC
